/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackWall: typeof import('./src/components/mainPage/backWall/BackWall.vue')['default']
    BackWallAbout: typeof import('./src/components/aboutUsPage/backWallAbout/BackWallAbout.vue')['default']
    BackWallBranch: typeof import('./src/components/branchPage/backWallBranch/BackWallBranch.vue')['default']
    BackWallNews: typeof import('./src/components/newsPage/backWallNews/BackWallNews.vue')['default']
    BackWallOutsideWindow: typeof import('./src/components/outsideWindowPage/backWallOutsideWindow/BackWallOutsideWindow.vue')['default']
    BackWallTeam: typeof import('./src/components/teamPage/backWallTeam/BackWallTeam.vue')['default']
    BlockCoaches: typeof import('./src/components/teamPage/mainTeam/BlockCoaches.vue')['default']
    BlockFan: typeof import('./src/components/teamPage/mainTeam/BlockFan.vue')['default']
    BlockFighters: typeof import('./src/components/teamPage/mainTeam/BlockFighters.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogCoache: typeof import('./src/components/AllDialogs/dialogCoache/DialogCoache.vue')['default']
    DialogFighter: typeof import('./src/components/AllDialogs/dialogFighter/DialogFighter.vue')['default']
    DialogNews: typeof import('./src/components/AllDialogs/dialogNews/DialogNews.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeadAbout: typeof import('./src/components/aboutUsPage/headAbout/HeadAbout.vue')['default']
    HeadBranch: typeof import('./src/components/branchPage/headBranch/HeadBranch.vue')['default']
    HeadNews: typeof import('./src/components/newsPage/headNews/HeadNews.vue')['default']
    HeadOutsideWindow: typeof import('./src/components/outsideWindowPage/headOutsideWindow/HeadOutsideWindow.vue')['default']
    HeadPicture: typeof import('./src/components/mainPage/headPicture/HeadPicture.vue')['default']
    HeadTeam: typeof import('./src/components/teamPage/headTeam/HeadTeam.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainAbautUs: typeof import('./src/components/mainPage/mainAboutUs/MainAbautUs.vue')['default']
    MainAbout: typeof import('./src/components/aboutUsPage/mainAbout/MainAbout.vue')['default']
    MainBlockNews: typeof import('./src/components/newsPage/mainNews/MainBlockNews.vue')['default']
    MainBlockOutsideWindow: typeof import('./src/components/outsideWindowPage/mainBlockOutsideWindow/MainBlockOutsideWindow.vue')['default']
    MainBlockTeam: typeof import('./src/components/teamPage/mainTeam/MainBlockTeam.vue')['default']
    MainBranch: typeof import('./src/components/branchPage/mainBranch/MainBranch.vue')['default']
    MainNews: typeof import('./src/components/mainPage/mainNews/MainNews.vue')['default']
    MainPartners: typeof import('./src/components/mainPage/mainPartners/MainPartners.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
